### ISSUE TITLE
swift使用pod集成SDK时，Bridging-Header.h文件里的路径应该怎么写？

### ISSUE THREAD

**Issue by rayman-v** [Meiqia/MeiqiaSDK-iOS#120]
![image](https://cloud.githubusercontent.com/assets/4557143/16404918/c06ec04c-3d35-11e6-9937-958c294a059a.png)
![image](https://cloud.githubusercontent.com/assets/4557143/16404930/d8b4949c-3d35-11e6-9e46-4ec4bed9fa6b.png)

**Comment by IanLuo** [comment]
这是个 podspec 的问题，新版本里面已经解决，稍等新版本发布后更新一下就可以了，后者可以加一个我们的开发 qq 群 （295646206），急用的话可以吧文件给你直接指定。
