### ISSUE TITLE
升级sdk 提示 "MQMessageFactoryHelper.h" not found

### ISSUE THREAD

**Issue by buoge** [Meiqia/MeiqiaSDK-iOS#146]
在 MQServiceToViewInterface 中 ：有如下引用#import "MQMessageFactoryHelper.h" ，MQVisialMessageFactory.h 
我们之前引用方式是手动引用的，没有这个文件，直接覆盖sdk目录后，发现上述一些文件存在目录中但没加入xcode 索引目录需要手动拉进来,解决方法是把xcode中之前的MessageModels文件引用清空在把文件全部从新拖进去

**Comment by IanLuo** [comment]
由于新增了文件，直接在 finder 中覆盖原来的文件夹，但是新的文件并没有被加到工程中去。
建议的做法是，每次更新版本，把 SDK 从工程中移除「remove reference」，然后重新从 finder 中拖到工程。
