### ISSUE TITLE
美洽接起来真**糟心，没入坑的千万别买

### ISSUE THREAD

**Issue by gaoshanyu** [Meiqia/MeiqiaSDK-iOS#187]
1. carthage：

```
*** Building scheme "Meiqia" in Meiqia-SDK-Demo.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project xxx/Carthage/Checkouts/MeiqiaSDK-iOS/Meiqia-SDK-Demo/Meiqia-SDK-Demo.xcodeproj -scheme Meiqia -configuration Release -derivedDataPath ～/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/MeiqiaSDK-iOS/v3.4.7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/33/16l0lj_94zd89wjd17qmr95m0000gn/T/MeiqiaSDK-iOS SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in xxx/Carthage/Checkouts/MeiqiaSDK-iOS)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/33/16l0lj_94zd89wjd17qmr95m0000gn/T/carthage-xcodebuild.DC9U97.log
```

2. pods：

`objc[44343]: Class MQModel is implemented in both ~/Library/Developer/CoreSimulator/Devices/290ABA71-A5AA-4474-8658-4277905A3818/data/Containers/Bundle/Application/10AEC2FA-FACD-47BA-8AAF-93F92F9042EF/demo.app/Frameworks/Meiqia.framework/Meiqia (0x1130eca68) and ~/Library/Developer/CoreSimulator/Devices/290ABA71-A5AA-4474-8658-4277905A3818/data/Containers/Bundle/Application/10AEC2FA-FACD-47BA-8AAF-93F92F9042EF/demo.app/target (0x10c510770). One of the two will be used. Which one is undefined.`

3. 自行导入：
警告有400+

总结下来就是，心累

**Comment by ccnyou** [comment]
亲，你的 MQModel 重复定义了，把工程的改个名吧。
