### ISSUE TITLE
关于用户资料的更新问题

### ISSUE THREAD

**Issue by JTL1992** [Meiqia/MeiqiaSDK-iOS#200]
你好，我尝试每次打开客服界面时都传最新的用户资料，但后台没有更新，难道用户资料只有第一次传递有效，之后的不会覆盖之前的信息么？

**Comment by xiaocainiao892** [comment]
使用MQChatViewManager中这个方法更新
/**
 *  设置顾客的自定义信息
 *
 *  @param clientInfo 顾客的自定义信息
    @param override 是否强制更新，如果不设置此值为 YES，设置只有第一次有效。
 */
- (void)setClientInfo:(NSDictionary *)clientInfo override:(BOOL)override;
