### ISSUE TITLE
Xcode 12.5 报错

### ISSUE THREAD

**Issue by CaiChenghan** [Meiqia/MeiqiaSDK-iOS#206]
## Xcode 12.5 美洽报错，具体看图。

![image](https://user-images.githubusercontent.com/9568389/116223292-f819eb00-a781-11eb-900b-aaeeabcf14fd.png)
![image](https://user-images.githubusercontent.com/9568389/116223310-fd773580-a781-11eb-8c4c-6d50a396c553.png)
![393D0912837910F4F52712949CBC39F3](https://user-images.githubusercontent.com/9568389/116224046-c190a000-a782-11eb-99e4-d8382fc2c193.jpg)

**Comment by xiaocainiao892** [comment]
可以UI层自己先改，改成[[TTTAttributedLabel alloc] initWithFrame:CGRectZero];  下个版本会优化

**Comment by LeeSen11** [comment]
@xiaocainiao892 你好，想问一下，下个版本大概什么时候会发布？

**Comment by xiaocainiao892** [comment]
今天
